apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    type: backend
    app: nodeapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  template:
    metadata:
      name: nodeapppod
      labels:
        type: backend
        app: nodeapp
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nodeappcontainer
          image: us-central1-docker.pkg.dev/jenkins-with-gcp-445915/app-node-gke/app-node-image:v1.0.0
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 80